abi = [
    {"constant":False,"inputs":[
    {"name":"_character","type":"uint256"},
    {"name":"_stats","type":"uint256"}],"name":"editStats","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x0012b568"},
    {"constant":True,"inputs":[
    {"name":"_character","type":"uint256"}],"name":"viewXP","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x01e38a4e"},
    {"constant":False,"inputs":[
    {"name":"_who","type":"address"},
    {"name":"_amount","type":"uint256"}],"name":"addToAccountGold","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x07f8b527"},
    {"constant":False,"inputs":[
    {"name":"_who","type":"address"},
    {"name":"_amount","type":"uint256"}],"name":"removeAccountGold","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x0a7867d2"},
    {"constant":True,"inputs":[
    {"name":"_who","type":"address"}],"name":"experienceOf","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x0b1c82b2"},
    {"constant":False,"inputs":[
    {"name":"_character","type":"uint256"},
    {"name":"_item","type":"uint256"},
    {"name":"_amount","type":"uint256"}],"name":"useItems","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x0cf62ea2"},
    {"constant":True,"inputs":[
    {"name":"","type":"uint256"},
    {"name":"","type":"uint256"}],"name":"gravestoneMap","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x0e62825d"},
    {"constant":True,"inputs":[
    {"name":"_player","type":"address"}],"name":"viewCharacters","outputs":[
    {"name":"","type":"uint256[]"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x293ddcfe"},
    {"constant":True,"inputs":[
    {"name":"","type":"uint256"}],"name":"experienceMap","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x31d8d3db"},
    {"constant":True,"inputs":[
    {"name":"_character","type":"uint256"},
    {"name":"_equipmentIndex","type":"uint256"}],"name":"hasEquipment","outputs":[
    {"name":"","type":"bool"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x41c42a0b"},
    {"constant":False,"inputs":[
    {"name":"_character","type":"uint256"},
    {"name":"_XPAmount","type":"uint256"},
    {"name":"_goldAmount","type":"uint256"},
    {"name":"_player","type":"address"}],"name":"giveXPandGold","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x425bde5b"},
    {"constant":True,"inputs":[
    {"name":"","type":"uint256"}],"name":"runTotalMap","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x496b045a"},
    {"constant":False,"inputs":[
    {"name":"_character","type":"uint256"},
    {"name":"_amount","type":"uint256"}],"name":"giveHealth","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x4fda4855"},
    {"constant":True,"inputs":[
    {"name":"","type":"uint256"}],"name":"statsMap","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x528baab4"},
    {"constant":True,"inputs":[],"name":"totalCharacters","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x6394344b"},
    {"constant":False,"inputs":[
    {"name":"_who","type":"address"}],"name":"goldOf","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x70425138"},
    {"constant":False,"inputs":[
    {"name":"_default","type":"bool"},
    {"name":"_setupStage","type":"bool"},
    {"name":"_player","type":"address"}],"name":"rollCharacter","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x723dcddb"},
    {"constant":True,"inputs":[
    {"name":"_character","type":"uint256"}],"name":"viewHTP","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x739fbf30"},
    {"constant":True,"inputs":[
    {"name":"","type":"uint256"}],"name":"baseStatsMap","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x73f505e0"},
    {"constant":True,"inputs":[
    {"name":"_character","type":"uint256"}],"name":"viewCurrentHealth","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x7cf4f0e3"},
    {"constant":True,"inputs":[
    {"name":"","type":"uint256"}],"name":"goldMap","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x7d064d7d"},
    {"constant":False,"inputs":[
    {"name":"_to","type":"address"},
    {"name":"_from","type":"address"},
    {"name":"_amount","type":"uint256"}],"name":"transferAccountGold","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x7d4be10c"},
    {"constant":False,"inputs":[
    {"name":"_character","type":"uint256"},
    {"name":"_inventory","type":"uint256"}],"name":"editInventory","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x808bf415"},
    {"constant":False,"inputs":[
    {"name":"_who","type":"address"},
    {"name":"_amount","type":"uint256"}],"name":"removeAccountExperience","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x81862de7"},
    {"constant":True,"inputs":[],"name":"baseStats","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x81edfa4a"},
    {"constant":True,"inputs":[
    {"name":"_character","type":"uint256"}],"name":"viewGravestone","outputs":[
    {"name":"","type":"uint256[3]"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x8344eda8"},
    {"constant":True,"inputs":[
    {"name":"_player","type":"address"}],"name":"viewDeadCharacters","outputs":[
    {"name":"","type":"uint256[]"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x9d1be612"},
    {"constant":True,"inputs":[
    {"name":"","type":"uint256"}],"name":"equipmentMap","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xa057a810"},
    {"constant":True,"inputs":[
    {"name":"_character","type":"uint256"}],"name":"viewWeapons","outputs":[
    {"name":"","type":"uint256[2]"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xa38e8142"},
    {"constant":True,"inputs":[
    {"name":"_character","type":"uint256"}],"name":"viewGoldAndXP","outputs":[
    {"name":"","type":"uint256"},
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xa41976a1"},
    {"constant":False,"inputs":[
    {"name":"_character","type":"uint256"},
    {"name":"_stats","type":"uint256"},
    {"name":"_equipment","type":"uint256"},
    {"name":"_loot","type":"uint256"}],"name":"editCharacter","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0xa580cf9d"},
    {"constant":True,"inputs":[
    {"name":"_character","type":"uint256"}],"name":"viewEquipment","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xa65c5a84"},
    {"constant":True,"inputs":[
    {"name":"","type":"address"},
    {"name":"","type":"uint256"}],"name":"accountCharacters","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xa90a24cd"},
    {"constant":True,"inputs":[
    {"name":"","type":"address"}],"name":"accountGold","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xa9346c5f"},
    {"constant":True,"inputs":[
    {"name":"_player","type":"address"}],"name":"viewActiveCharacter","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xb22839e4"},
    {"constant":False,"inputs":[
    {"name":"_character","type":"uint256"},
    {"name":"_runID","type":"uint256"}],"name":"addToRuns","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0xb526d806"},
    {"constant":False,"inputs":[
    {"name":"_character","type":"uint256"},
    {"name":"_item","type":"uint256"},
    {"name":"_slot","type":"uint256"}],"name":"equipItem","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0xb7379531"},
    {"constant":True,"inputs":[
    {"name":"_character","type":"uint256"}],"name":"viewRuns","outputs":[
    {"name":"","type":"uint256[]"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xb83f9549"},
    {"constant":True,"inputs":[],"name":"equipmentCore","outputs":[
    {"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xc73ce939"},
    {"constant":False,"inputs":[
    {"name":"_character","type":"uint256"},
    {"name":"_killType","type":"uint256"},
    {"name":"_killID","type":"uint256"},
    {"name":"_block","type":"uint256"}],"name":"buildGravestone","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0xd0910bad"},
    {"constant":True,"inputs":[
    {"name":"","type":"address"}],"name":"playerMap","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xd214c6ca"},
    {"constant":False,"inputs":[
    {"name":"_character","type":"uint256"}],"name":"viewCharacter","outputs":[
    {"name":"","type":"uint256"},
    {"name":"","type":"uint256"},
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0xd3226eaf"},
    {"constant":True,"inputs":[
    {"name":"","type":"uint256"},
    {"name":"","type":"uint256"}],"name":"runMap","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xdc77b026"},
    {"constant":True,"inputs":[
    {"name":"","type":"address"}],"name":"accountExperience","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xe083e6db"},
    {"constant":True,"inputs":[
    {"name":"_character","type":"uint256"}],"name":"viewStats","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xe726ff50"},
    {"constant":False,"inputs":[
    {"name":"_character","type":"uint256"},
    {"name":"_equipment","type":"uint256"}],"name":"editEquipment","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0xeb5c65f9"},
    {"constant":True,"inputs":[
    {"name":"_player","type":"address"}],"name":"viewLastCharacter","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xf8e9fb05"},
    {"constant":True,"inputs":[
    {"name":"_character","type":"uint256"}],"name":"viewInventory","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xf90ea560"},
    {"constant":True,"inputs":[
    {"name":"_who","type":"address"}],"name":"hasCharacter","outputs":[
    {"name":"","type":"bool"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xf9dde607"},
    {"constant":True,"inputs":[
    {"name":"","type":"uint256"}],"name":"lootMap","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xfe882d64"},
    {"inputs":[
    {"name":"_equipmentCore","type":"address"}],"payable":False,"stateMutability":"nonpayable","type":"constructor","name":"constructor","signature":"constructor"}
]