abi = [{"constant":True,"inputs":
    [{"name":"_movePref1","type":"uint256"},{"name":"_movePref2","type":"uint256"},{"name":"_movePref3","type":"uint256"}],"name":"validatePreferences","outputs":
    [{"name":"","type":"bool"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x04747182"},{"constant":True,"inputs":
    [],"name":"totalCharacterDeaths","outputs":
    [{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x10818d91"},{"constant":False,"inputs":
    [],"name":"shutDown","outputs":
    [],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x10b9e583"},{"constant":True,"inputs":
    [],"name":"nextRun","outputs":
    [{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x36802d7d"},{"constant":False,"inputs":
    [{"name":"_character","type":"uint256"}],"name":"exitFeature","outputs":
    [],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x426a160e"},{"constant":True,"inputs":
    [],"name":"MAX_ROOMS","outputs":
    [{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x427eaabb"},{"constant":True,"inputs":
    [],"name":"bestiaryCore","outputs":
    [{"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x4adae299"},{"constant":False,"inputs":
    [{"name":"_character","type":"uint256"}],"name":"viewSeedMap","outputs":
    [{"name":"","type":"uint256"}],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x66e5e78f"},{"constant":True,"inputs":
    [],"name":"totalCharactersEntered","outputs":
    [{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x6f8f2ce1"},{"constant":False,"inputs":
    [],"name":"renounceOwnership","outputs":
    [],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x715018a6"},{"constant":False,"inputs":
    [{"name":"_who","type":"address"}],"name":"revoke","outputs":
    [],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x74a8f103"},{"constant":True,"inputs":
    [{"name":"","type":"uint256"}],"name":"goldMap","outputs":
    [{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x7d064d7d"},{"constant":True,"inputs":
    [{"name":"_character","type":"uint256"}],"name":"viewFloor","outputs":
    [{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x7edba20b"},{"constant":True,"inputs":
    [{"name":"","type":"uint256"}],"name":"insideMap","outputs":
    [{"name":"","type":"bool"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x85a8966f"},{"constant":True,"inputs":
    [],"name":"benchmark","outputs":
    [{"name":"","type":"bool"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x8903c5a2"},{"constant":True,"inputs":
    [],"name":"owner","outputs":
    [{"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x8da5cb5b"},{"constant":True,"inputs":
    [],"name":"isOwner","outputs":
    [{"name":"","type":"bool"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x8f32d59b"},{"constant":True,"inputs":
    [{"name":"","type":"address"}],"name":"seedMap","outputs":
    [{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x93ab471c"},{"constant":False,"inputs":
    [{"name":"_character","type":"uint256"}],"name":"enterFloor","outputs":
    [],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x988790c6"},{"constant":False,"inputs":
    [{"name":"_character","type":"uint256"},{"name":"_changePrefs","type":"bool"},{"name":"_movePrefs","type":"uint256[3]"}],"name":"enterDungeon","outputs":
    [],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0xab92b955"},{"constant":True,"inputs":
    [],"name":"MAX_ENCOUNTERS","outputs":
    [{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xac08d2d2"},{"constant":True,"inputs":
    [{"name":"","type":"uint256"}],"name":"floorMap","outputs":
    [{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xaeb0156c"},{"constant":False,"inputs":
    [{"name":"_who","type":"address"}],"name":"authorize","outputs":
    [],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0xb6a5d7de"},{"constant":True,"inputs":
    [],"name":"isLive","outputs":
    [{"name":"","type":"bool"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xb8f7a665"},{"constant":True,"inputs":
    [],"name":"equipmentCore","outputs":
    [{"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xc73ce939"},{"constant":True,"inputs":
    [{"name":"","type":"uint256"}],"name":"seedMap","outputs":
    [{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xe1208010"},{"constant":True,"inputs":
    [],"name":"MAX_FLOORS","outputs":
    [{"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xeb218cb1"},{"constant":True,"inputs":
    [],"name":"combatCore","outputs":
    [{"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xf2312def"},{"constant":False,"inputs":
    [{"name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":
    [],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0xf2fde38b"},{"constant":True,"inputs":
    [],"name":"RNG","outputs":
    [{"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xf7149220"},{"constant":True,"inputs":
    [],"name":"characterCore","outputs":
    [{"name":"","type":"address"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xfc5f3e36"},{"constant":False,"inputs":
    [{"name":"_character","type":"uint256"}],"name":"enterFeature","outputs":
    [],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0xfe58d90d"},{"inputs":
    [{"name":"_entropy","type":"address"},{"name":"_combatCore","type":"address"},{"name":"_characterCore","type":"address"},{"name":"_equipmentCore","type":"address"},{"name":"_bestiaryCore","type":"address"}],"payable":False,"stateMutability":"nonpayable","type":"constructor","name":"constructor","signature":"constructor"},{"anonymous":False,"inputs":
    [{"indexed":True,"name":"_run","type":"uint256"},{"indexed":False,"name":"_room","type":"uint8"},{"indexed":False,"name":"_index","type":"uint256"}],"name":"EnteredRoom","type":"event","signature":"0x921f8c94f399a188bd1d7943ff183386a65e770c4dd19251dc80bf6c87a96e8f"},{"anonymous":False,"inputs":
    [{"indexed":True,"name":"_run","type":"uint256"},{"indexed":False,"name":"_encounter","type":"uint8"},{"indexed":False,"name":"_index","type":"uint256"},{"indexed":False,"name":"_creatureID","type":"uint256"},{"indexed":False,"name":"_roomIndex","type":"uint256"}],"name":"EnemyEncountered","type":"event","signature":"0x6ffe4a956d141f4582b11002b0cd333a94ce9d7e656ceb64198b38015b919066"},{"anonymous":False,"inputs":
    [{"indexed":True,"name":"_run","type":"uint256"},{"indexed":False,"name":"_loot","type":"uint256"},{"indexed":False,"name":"_index","type":"uint256"},{"indexed":False,"name":"_roomIndex","type":"uint256"},{"indexed":False,"name":"_dropped","type":"bool"}],"name":"LootEncountered","type":"event","signature":"0xd875a99da9d5aa56049b414e22cb62600f25a6c156f3b5e5800604dea85f1f30"},{"anonymous":False,"inputs":
    [{"indexed":True,"name":"_run","type":"uint256"},{"indexed":False,"name":"_trap","type":"uint8"},{"indexed":False,"name":"_index","type":"uint256"},{"indexed":False,"name":"_roomIndex","type":"uint256"},{"indexed":False,"name":"_damage","type":"uint256"}],"name":"TrapEncountered","type":"event","signature":"0x1272fab1b3ab3c7c1a7d733ea3d37a7163a32e2f06b93b282dc8daa0d7b4be72"},{"anonymous":False,"inputs":
    [{"indexed":True,"name":"_run","type":"uint256"},{"indexed":False,"name":"_amount","type":"uint256"},{"indexed":False,"name":"_index","type":"uint256"},{"indexed":False,"name":"_roomIndex","type":"uint256"}],"name":"CreditsEncountered","type":"event","signature":"0xc8c076d7ca0310078b0bffbe10b5abdb28f758607de31da987ee4fbbf3e79717"},{"anonymous":False,"inputs":
    [{"indexed":True,"name":"_run","type":"uint256"},{"indexed":False,"name":"_amount","type":"uint256"},{"indexed":False,"name":"_index","type":"uint256"}],"name":"ExperienceGained","type":"event","signature":"0xcaa434a316026b149e054a690120ac0358d069c9ffa5eda08124eb17c0f8dbdd"},{"anonymous":False,"inputs":
    [{"indexed":True,"name":"_run","type":"uint256"},{"indexed":False,"name":"_characterEquipment","type":"uint256"},{"indexed":False,"name":"_characterStats","type":"uint256"},{"indexed":False,"name":"_characterLoot","type":"uint256"},{"indexed":False,"name":"_characterExperience","type":"uint256"}],"name":"FloorEntered","type":"event","signature":"0x6d4b50120d27cd567317ccf8209a46a4000c39c72bf6d127bbf63f6e40bbe3db"},{"anonymous":False,"inputs":
    [{"indexed":True,"name":"_run","type":"uint256"},{"indexed":False,"name":"_type","type":"uint256"},{"indexed":False,"name":"_index","type":"uint256"},{"indexed":False,"name":"_roomIndex","type":"uint256"},{"indexed":False,"name":"_amount","type":"uint256"},{"indexed":False,"name":"_combatant","type":"uint256"}],"name":"EffectEncountered","type":"event","signature":"0x20a57522920d6015603de1cb680019d7239b0325d2b34603214f1c261a68135f"},{"anonymous":False,"inputs":
    [{"indexed":True,"name":"_run","type":"uint256"},{"indexed":False,"name":"_index","type":"uint256"},{"indexed":False,"name":"_target","type":"uint256"},{"indexed":False,"name":"_amount","type":"uint256"},{"indexed":False,"name":"_healthA","type":"uint256"},{"indexed":False,"name":"_healthB","type":"uint256"}],"name":"LongRangeCombat","type":"event","signature":"0x7c2b2c0b44c11e93ca2518564190facac5b1356d457427c80780c6e0e4b0d904"},{"anonymous":False,"inputs":
    [{"indexed":True,"name":"previousOwner","type":"address"},{"indexed":True,"name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event","signature":"0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0"}]