abi=[
    {"constant":False,"inputs":[
    {"name":"_equipment","type":"uint256"},
    {"name":"_HTP","type":"int256"},
    {"name":"_INT","type":"int256"},
    {"name":"_ATK","type":"int256"},
    {"name":"_DEF","type":"int256"},
    {"name":"_STR","type":"int256"},
    {"name":"_SPD","type":"int256"},
    {"name":"_WGT","type":"int256"},
    {"name":"_VSN","type":"int256"},
    {"name":"_LCK","type":"uint256"},
    {"name":"_XGP","type":"uint256"}],"name":"editEquipmentBase","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x19c89c55"},
    {"constant":False,"inputs":[
    {"name":"_equipment","type":"uint256"},
    {"name":"_type","type":"uint256"},
    {"name":"_set","type":"uint256"},
    {"name":"_slot","type":"uint256"},
    {"name":"_weight","type":"uint256"},
    {"name":"_hands","type":"uint256"},
    {"name":"_cost","type":"uint256"}],"name":"editEquipmentExtras","outputs":[],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x36cd8ccf"},
    {"constant":True,"inputs":[
    {"name":"","type":"uint256"}],"name":"equipment","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0x65b817e6"},
    {"constant":False,"inputs":[
    {"name":"_HTP","type":"int256"},
    {"name":"_INT","type":"int256"},
    {"name":"_ATK","type":"int256"},
    {"name":"_DEF","type":"int256"},
    {"name":"_STR","type":"int256"},
    {"name":"_SPD","type":"int256"},
    {"name":"_WGT","type":"int256"},
    {"name":"_VSN","type":"int256"},
    {"name":"_LCK","type":"uint256"},
    {"name":"_XGP","type":"uint256"}],"name":"newMicroEquipmentBase","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0x72bec7cf"},
    {"constant":True,"inputs":[
    {"name":"_equipmentIndex","type":"uint256"}],"name":"viewEquipment","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"view","type":"function","signature":"0xa65c5a84"},
    {"constant":False,"inputs":[
    {"name":"_equipmentBase","type":"uint256"},
    {"name":"_type","type":"uint256"},
    {"name":"_set","type":"uint256"},
    {"name":"_slot","type":"uint256"},
    {"name":"_weight","type":"uint256"},
    {"name":"_hands","type":"uint256"},
    {"name":"_cost","type":"uint256"}],"name":"setMicroEquipmentExtras","outputs":[
    {"name":"","type":"uint256"}],"payable":False,"stateMutability":"nonpayable","type":"function","signature":"0xf17b4e01"},
    {"inputs":[],"payable":False,"stateMutability":"nonpayable","type":"constructor","name":"constructor","signature":"constructor"}
]